# Generated by Django 5.1.15 on 2026-05-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='section_type',
            field=models.CharField(choices=[('abstract', 'Abstract'), ('introduction', 'Introduction'), ('methods', 'Methods'), ('results', 'Results'), ('discussion', 'Discussion'), ('conclusion', 'Conclusion'), ('references', 'References'), ('summary', 'Summary'), ('purpose', 'Purpose'), ('scope', 'Scope'), ('requirements', 'Requirements'), ('procedure', 'Procedure'), ('troubleshooting', 'Troubleshooting'), ('faq', 'FAQ'), ('glossary', 'Glossary'), ('appendix', 'Appendix'), ('overview', 'Overview'), ('policy', 'Policy'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
