# Generated by Django 5.1.15 on 2026-05-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentchunk_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='content_type',
            field=models.CharField(choices=[('prose', 'Prose'), ('table', 'Table'), ('list', 'List'), ('code', 'Code')], default='prose', max_length=10),
        ),
    ]
